# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "air"

[build]
  # Binary file yields from `cmd`.
  # bin = "./air/main -s ./DATABASE/orig/loot/loot/Ply/loot_vox10_1000.ply"
  bin = "./air/gui"
  # Just plain old shell command. You could use `make` as well.
  # cmd = "go build -o ./air/main ./cmd/pccbi"
  cmd = "./scripts/fyne_build_with_filter.sh"
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000
  # Ignore these filename extensions or directories.
  exclude_dir = ["air", "tmp", "DATABASE"]
  # Exclude files.
  exclude_file = []
  # Exclude files that match a regular expression.
  exclude_regex = []
  # Exclude unchanged files.
  exclude_unchanged = false
  # Follow symlink for directories
  follow_symlink = false
  # Customize binary.
  full_bin = ""
  # Watch these directories if you specified.
  include_dir = []
  # Watch these filename extensions.
  include_ext = ["go"]
  # Delay after sending Interrupt signal
  kill_delay = "0s"
  # This log file places in your tmp_dir.
  log = "build-errors.log"
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  # Stop running old binary when build errors occur.
  stop_on_error = true

[color]
  # Customize each part's color. If no color found, use the raw app log.
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  # Show log time
  time = false

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true
